import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Button, Container } from "reactstrap";
import StepOne from "../components/StepOne";
import StepTwo from "../components/StepTwo";
import { useRecoilState } from "recoil";
import {
  personalInfoList,
  educationList,
  experienceList,
  projectList,
  skillList,
  socialLinksList,
} from "../atom/atom";
import StepThree from "../components/StepThree";
import StepFour from "../components/StepFour";
import StepFIve from "../components/StepFIve";
import StepSix from "../components/StepSix";
import StepFinal from "../components/StepFinal";
import axios from 'axios'

export default function Playground() {
  const [currentStep, setCurrentStep] = useState(1);
  const [personalInfo, setPersonalInfo] = useRecoilState(personalInfoList);
  const [educations, setEducations] = useRecoilState(educationList);
  const [experiences, setExpeiences] = useRecoilState(experienceList);
  const [projects, setProjects] = useRecoilState(projectList);
  const [skills, setSkills] = useRecoilState(skillList);
  const [socials, setSocials] = useRecoilState(socialLinksList);


  const NextCLicked = () => {
    setCurrentStep(currentStep + 1);
  };

  const PreviousCLicked = () => {
    setCurrentStep(currentStep - 1);
  };

  const download = () => {
    axios.get('/api/v1')  
    .then(({data}) => {
      console.log(data)
    })
    .catch( (err) => {
      console.log(err)
    })
    // console.log({
    //   personalInfo,
    //   educations,
    //   experiences,
    //   projects,
    //   skills,
    //   socials,
    // });
  };

  useEffect(() => {
    download()
  }, [])

  const showComponents = () => {
    switch (currentStep) {
      case 1:
        return <StepOne nextStep={NextCLicked} prevStep={PreviousCLicked} />;

      case 2:
        return <StepTwo nextStep={NextCLicked} prevStep={PreviousCLicked} />;

      case 3:
        return <StepThree nextStep={NextCLicked} prevStep={PreviousCLicked} />;

      case 4:
        return <StepFour nextStep={NextCLicked} prevStep={PreviousCLicked} />;

      case 5:
        return <StepFIve nextStep={NextCLicked} prevStep={PreviousCLicked} />;

      case 6:
        return <StepSix nextStep={NextCLicked} prevStep={PreviousCLicked} />;

      case 7:
        return <StepFinal download={download} prevStep={PreviousCLicked} />;

      default:
        break;
    }
  };

  return (
    <>
      <Head>
        <title>Resume Builder - By Roqeeb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="resume__builder d-flex justify-content-center">
        <div className="all__wraper w-100">
          <div className="steps">
            <ul className="progressBar">
              <li className="active">Personal Information</li>
              <li className={`${currentStep >= 2 ? "active " : ""}`}>
                Education
              </li>
              <li className={`${currentStep >= 3 ? "active" : ""}`}>
                Experience
              </li>
              <li className={`${currentStep >= 4 ? "active" : ""}`}>
                Projects
              </li>
              <li className={`${currentStep >= 5 ? "active" : ""}`}>Skills</li>
              <li className={`${currentStep >= 6 ? "active" : ""}`}>Socials</li>
            </ul>
          </div>
          {/* <div className="backToHome">
            <Link href="/">
              <a>Resume Builder</a>
            </Link>
          </div> */}
          <section className="comp__wraper">
            <div className="playground m-auto">
              <div className="overflow-hidden">
                <div className="show">{showComponents()}</div>
              </div>
            </div>
          </section>

          {/* <section className="btn__wrapper">
            <div className="btns d-flex justify-content-between m-auto">
              <Button
                disabled={currentStep === 1 ? true : false}
                onClick={PreviousCLicked}
              >
                Prev
              </Button>

              <Button
                className="next"
                disabled={currentStep === totalSteps ? true : false}
                onClick={NextCLicked}
              >
                Next
              </Button>
            </div>
          </section> */}
        </div>
      </main>
    </>
  );
}
