import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { Button, Container } from "reactstrap";
import StepOne from "../components/StepOne";
import StepTwo from "../components/StepTwo";
import { useRecoilState } from "recoil";
import { firstNameState, lastNameState, middleNameState } from "../atom/atom";
import StepThree from "../components/StepThree";
import StepFour from "../components/StepFour";

export default function Playground() {
  const [currentStep, setCurrentStep] = useState(1);
  const [totalSteps, setTotalSteps] = useState(5);

  /* Pesonal Information */
  const [firstName, setFirstName] = useRecoilState(firstNameState);
  const [lastName, setLastName] = useRecoilState(lastNameState);
  const [middleName, setMiddleName] = useRecoilState(middleNameState);

  /* Work Experience */

  /* Institution */

  /* Hobbies */

  /* Skills */

  const NextCLicked = () => {
    setCurrentStep(currentStep + 1);
  };

  const PreviousCLicked = () => {
    setCurrentStep(currentStep - 1);
  };

  const showComponents = () => {
    switch (currentStep) {
      case 1:
        return <StepOne nextStep={NextCLicked} prevStep={PreviousCLicked} />;

      case 2:
        return <StepTwo nextStep={NextCLicked} prevStep={PreviousCLicked} />;

      case 3:
        return <StepThree nextStep={NextCLicked} prevStep={PreviousCLicked} />;

      case 4:
        return <StepFour nextStep={NextCLicked} prevStep={PreviousCLicked} />;
      default:
        break;
    }
  };

  const allData = () => {
    console.log({
      firstName,
      lastName,
      middleName,
    });
  };

  return (
    <>
      <Head>
        <title>Resume Builder - By Roqeeb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="resume__builder d-flex justify-content-center">
        <div className="p-5 w-100">
          <div className="steps">
            <ul className="progressBar">
              <li className="active">Personal Information</li>
              <li className={`${currentStep >= 2 ? "active " : ""}`}>
                Step Two
              </li>
              <li className={`${currentStep >= 3 ? "active" : ""}`}>
                Step Three
              </li>
              <li className={`${currentStep >= 4 ? "active" : ""}`}>
                Step Four
              </li>
              <li className={`${currentStep >= 5 ? "active" : ""}`}>
                Step Five
              </li>
            </ul>
          </div>
          {/* <div className="backToHome">
            <Link href="/">
              <a>Resume Builder</a>
            </Link>
          </div> */}
          <section className="comp__wraper">
            <div className="playground m-auto">
              <div className="show overflow-hidden">{showComponents()}</div>
            </div>
          </section>

          {/* <section className="btn__wrapper">
            <div className="btns d-flex justify-content-between m-auto">
              <Button
                disabled={currentStep === 1 ? true : false}
                onClick={PreviousCLicked}
              >
                Prev
              </Button>

              <Button
                className="next"
                disabled={currentStep === totalSteps ? true : false}
                onClick={NextCLicked}
              >
                Next
              </Button>
            </div>
          </section> */}
        </div>
      </main>
    </>
  );
}
